name: Beta release

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

defaults:
  run:
    working-directory: balancer-js

jobs:
  build_and_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo -n "$SIGNING_KEY" | base64 --decode | gpg --import
          git config --global user.name "gmbronco"
          git config --global user.email "gmbronco@users.noreply.github.com"
          git config user.signingkey A33ABD316E6629F6
          git config gpg.program /usr/bin/gpg
          yarn version --prerelease --no-git-tag-version
          export NEW_VERSION=$(jq -r '.version' package.json)
          git commit -S -am "chore: version bump v$NEW_VERSION"
          git tag "v$NEW_VERSION"
          yarn build
          yarn publish --non-interactive --tag beta
          git push

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
